### ISSUE TITLE
learning_rate not used

### ISSUE THREAD

**Issue by francisengelmann** [tatarchm/tangent_conv#12]
Hi Maxim,

it seems like the learning_rate you compute here is actually never used

https://github.com/tatarchm/tangent_conv/blob/cf79d660b00f2f5cb11d464e004a5424b547dbe2/util/model.py#L253
https://github.com/tatarchm/tangent_conv/blob/cf79d660b00f2f5cb11d464e004a5424b547dbe2/util/model.py#L255

**Comment by tatarchm** [comment]
I believe you are right. I'll fix it.
