### ISSUE TITLE
'voxel_down_sample_for_surface_conv' is not defined

### ISSUE THREAD

**Issue by tejaskhot** [tatarchm/tangent_conv#3]
It is used here, but does not seem to be defined anywhere in the code repository and throws up an error.

https://github.com/tatarchm/tangent_conv/blob/688fac5144c0194de4ece2855afe077e97a07411/util/precompute.py#L73

Same for some of the other functions used in `precompute.py`

**Comment by tatarchm** [comment]
I cannot reproduce the issue. This function is provided through the python binding of Open3D.

Could you please provide more details? Did you build [Open3D](https://github.com/tatarchm/Open3D) and update the path values in 'path_config.py'? What command do you execute when the error pops up?

**Comment by tejaskhot** [comment]
Yes, I built Open3D from the repo as suggested and modified the paths in `path_config.py`. I get the following error when running the precompute script:

```
git_repos/tangent_conv$ python tc.py experiments/stanford/dhnrgb/config.json --precompute
:: precompute
processing scan: Area_1_conferenceRoom_1, rot: 0
Traceback (most recent call last):
  File "tc.py", line 21, in <module>
    run_precompute(config)
  File "util/precompute.py", line 73, in run_precompute
    pcd_colors_down = voxel_down_sample_for_surface_conv(pcd_colors, multiplier*p.min_cube_size,
NameError: name 'voxel_down_sample_for_surface_conv' is not defined
```

Also, when I did a code search in the Open3D repo, I could find no results for this function name.

**Comment by tatarchm** [comment]
Do you execute the script with the same python version as the one used while compiling Open3D?

**Comment by tejaskhot** [comment]
Yes.

**Comment by tatarchm** [comment]
Could you please provide the contents of your 'path_config.py'?

**Comment by tejaskhot** [comment]
The contents for `/usr1/home/tkhot/git_repos/tangent_conv/util/path_config.py`
```
import sys

open3d_path = '/usr1/home/tkhot/git_repos/Open3D/build/lib/'
tc_path = '/usr1/home/tkhot/git_repos/tangent_conv/'

sys.path.append(open3d_path)
from py3d import *

def get_tc_path():
	return tc_path
```

**Comment by tatarchm** [comment]
Looks good to me. @syncle, do you have an idea what the problem may be?

**Comment by syncle** [comment]
``voxel_down_sample_for_surface_conv`` is defined here:
https://github.com/tatarchm/Open3D/src/Python/Core/py3d_pointcloud.cpp#L112
so it should run if you properly clone https://github.com/tatarchm/Open3D.

> Also, when I did a code search in the Open3D repo, I could find no results for this function name.

The Open3D repo for tangent convolution is forked repo. Github does not provide code search for forked repo.

**Comment by tejaskhot** [comment]
A global installation of Open3D from the main repo was getting detected which was causing this issue. Thanks!
